version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - npm install
      - zip -r function.zip app.js node_modules package.json

artifacts:
  files:
    - function.zip
